//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NusantaraModel", "FK_PlayerSoal_Player", "Player", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NusantaraGame.Player), "PlayerSoal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NusantaraGame.PlayerSoal), true)]
[assembly: EdmRelationshipAttribute("NusantaraModel", "FK_PlayerSoal_Provinsi", "Provinsi", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NusantaraGame.Provinsi), "PlayerSoal", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(NusantaraGame.PlayerSoal), true)]

#endregion

namespace NusantaraGame
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NusantaraEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NusantaraEntities2 object using the connection string found in the 'NusantaraEntities2' section of the application configuration file.
        /// </summary>
        public NusantaraEntities2() : base("name=NusantaraEntities2", "NusantaraEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NusantaraEntities2 object.
        /// </summary>
        public NusantaraEntities2(string connectionString) : base(connectionString, "NusantaraEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NusantaraEntities2 object.
        /// </summary>
        public NusantaraEntities2(EntityConnection connection) : base(connection, "NusantaraEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Player> Players
        {
            get
            {
                if ((_Players == null))
                {
                    _Players = base.CreateObjectSet<Player>("Players");
                }
                return _Players;
            }
        }
        private ObjectSet<Player> _Players;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PlayerSoal> PlayerSoals
        {
            get
            {
                if ((_PlayerSoals == null))
                {
                    _PlayerSoals = base.CreateObjectSet<PlayerSoal>("PlayerSoals");
                }
                return _PlayerSoals;
            }
        }
        private ObjectSet<PlayerSoal> _PlayerSoals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Provinsi> Provinsis
        {
            get
            {
                if ((_Provinsis == null))
                {
                    _Provinsis = base.CreateObjectSet<Provinsi>("Provinsis");
                }
                return _Provinsis;
            }
        }
        private ObjectSet<Provinsi> _Provinsis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Setting> Settings
        {
            get
            {
                if ((_Settings == null))
                {
                    _Settings = base.CreateObjectSet<Setting>("Settings");
                }
                return _Settings;
            }
        }
        private ObjectSet<Setting> _Settings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Players EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayers(Player player)
        {
            base.AddObject("Players", player);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PlayerSoals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayerSoals(PlayerSoal playerSoal)
        {
            base.AddObject("PlayerSoals", playerSoal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Provinsis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProvinsis(Provinsi provinsi)
        {
            base.AddObject("Provinsis", provinsi);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSettings(Setting setting)
        {
            base.AddObject("Settings", setting);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NusantaraModel", Name="Player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="playerId">Initial value of the PlayerId property.</param>
        public static Player CreatePlayer(global::System.Int32 playerId)
        {
            Player player = new Player();
            player.PlayerId = playerId;
            return player;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayerId
        {
            get
            {
                return _PlayerId;
            }
            set
            {
                if (_PlayerId != value)
                {
                    OnPlayerIdChanging(value);
                    ReportPropertyChanging("PlayerId");
                    _PlayerId = StructuralObject.SetValidValue(value, "PlayerId");
                    ReportPropertyChanged("PlayerId");
                    OnPlayerIdChanged();
                }
            }
        }
        private global::System.Int32 _PlayerId;
        partial void OnPlayerIdChanging(global::System.Int32 value);
        partial void OnPlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LastNyawa
        {
            get
            {
                return _LastNyawa;
            }
            set
            {
                OnLastNyawaChanging(value);
                ReportPropertyChanging("LastNyawa");
                _LastNyawa = StructuralObject.SetValidValue(value, "LastNyawa");
                ReportPropertyChanged("LastNyawa");
                OnLastNyawaChanged();
            }
        }
        private Nullable<global::System.Int32> _LastNyawa;
        partial void OnLastNyawaChanging(Nullable<global::System.Int32> value);
        partial void OnLastNyawaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LastScore
        {
            get
            {
                return _LastScore;
            }
            set
            {
                OnLastScoreChanging(value);
                ReportPropertyChanging("LastScore");
                _LastScore = StructuralObject.SetValidValue(value, "LastScore");
                ReportPropertyChanged("LastScore");
                OnLastScoreChanged();
            }
        }
        private Nullable<global::System.Int32> _LastScore;
        partial void OnLastScoreChanging(Nullable<global::System.Int32> value);
        partial void OnLastScoreChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NusantaraModel", "FK_PlayerSoal_Player", "PlayerSoal")]
        public EntityCollection<PlayerSoal> PlayerSoals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PlayerSoal>("NusantaraModel.FK_PlayerSoal_Player", "PlayerSoal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PlayerSoal>("NusantaraModel.FK_PlayerSoal_Player", "PlayerSoal", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NusantaraModel", Name="PlayerSoal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PlayerSoal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PlayerSoal object.
        /// </summary>
        /// <param name="soalId">Initial value of the SoalId property.</param>
        /// <param name="playerId">Initial value of the PlayerId property.</param>
        public static PlayerSoal CreatePlayerSoal(global::System.Int32 soalId, global::System.Int32 playerId)
        {
            PlayerSoal playerSoal = new PlayerSoal();
            playerSoal.SoalId = soalId;
            playerSoal.PlayerId = playerId;
            return playerSoal;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SoalId
        {
            get
            {
                return _SoalId;
            }
            set
            {
                if (_SoalId != value)
                {
                    OnSoalIdChanging(value);
                    ReportPropertyChanging("SoalId");
                    _SoalId = StructuralObject.SetValidValue(value, "SoalId");
                    ReportPropertyChanged("SoalId");
                    OnSoalIdChanged();
                }
            }
        }
        private global::System.Int32 _SoalId;
        partial void OnSoalIdChanging(global::System.Int32 value);
        partial void OnSoalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayerId
        {
            get
            {
                return _PlayerId;
            }
            set
            {
                OnPlayerIdChanging(value);
                ReportPropertyChanging("PlayerId");
                _PlayerId = StructuralObject.SetValidValue(value, "PlayerId");
                ReportPropertyChanged("PlayerId");
                OnPlayerIdChanged();
            }
        }
        private global::System.Int32 _PlayerId;
        partial void OnPlayerIdChanging(global::System.Int32 value);
        partial void OnPlayerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NusantaraModel", "FK_PlayerSoal_Player", "Player")]
        public Player Player
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("NusantaraModel.FK_PlayerSoal_Player", "Player").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("NusantaraModel.FK_PlayerSoal_Player", "Player").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Player> PlayerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Player>("NusantaraModel.FK_PlayerSoal_Player", "Player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Player>("NusantaraModel.FK_PlayerSoal_Player", "Player", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NusantaraModel", "FK_PlayerSoal_Provinsi", "Provinsi")]
        public Provinsi Provinsi
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinsi>("NusantaraModel.FK_PlayerSoal_Provinsi", "Provinsi").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinsi>("NusantaraModel.FK_PlayerSoal_Provinsi", "Provinsi").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Provinsi> ProvinsiReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provinsi>("NusantaraModel.FK_PlayerSoal_Provinsi", "Provinsi");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Provinsi>("NusantaraModel.FK_PlayerSoal_Provinsi", "Provinsi", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NusantaraModel", Name="Provinsi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Provinsi : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Provinsi object.
        /// </summary>
        /// <param name="soalId">Initial value of the SoalId property.</param>
        public static Provinsi CreateProvinsi(global::System.Int32 soalId)
        {
            Provinsi provinsi = new Provinsi();
            provinsi.SoalId = soalId;
            return provinsi;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SoalId
        {
            get
            {
                return _SoalId;
            }
            set
            {
                if (_SoalId != value)
                {
                    OnSoalIdChanging(value);
                    ReportPropertyChanging("SoalId");
                    _SoalId = StructuralObject.SetValidValue(value, "SoalId");
                    ReportPropertyChanged("SoalId");
                    OnSoalIdChanged();
                }
            }
        }
        private global::System.Int32 _SoalId;
        partial void OnSoalIdChanging(global::System.Int32 value);
        partial void OnSoalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Soal
        {
            get
            {
                return _Soal;
            }
            set
            {
                OnSoalChanging(value);
                ReportPropertyChanging("Soal");
                _Soal = StructuralObject.SetValidValue(value, true, "Soal");
                ReportPropertyChanged("Soal");
                OnSoalChanged();
            }
        }
        private global::System.String _Soal;
        partial void OnSoalChanging(global::System.String value);
        partial void OnSoalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UrlGambar
        {
            get
            {
                return _UrlGambar;
            }
            set
            {
                OnUrlGambarChanging(value);
                ReportPropertyChanging("UrlGambar");
                _UrlGambar = StructuralObject.SetValidValue(value, true, "UrlGambar");
                ReportPropertyChanged("UrlGambar");
                OnUrlGambarChanged();
            }
        }
        private global::System.String _UrlGambar;
        partial void OnUrlGambarChanging(global::System.String value);
        partial void OnUrlGambarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LevelSoal
        {
            get
            {
                return _LevelSoal;
            }
            set
            {
                OnLevelSoalChanging(value);
                ReportPropertyChanging("LevelSoal");
                _LevelSoal = StructuralObject.SetValidValue(value, "LevelSoal");
                ReportPropertyChanged("LevelSoal");
                OnLevelSoalChanged();
            }
        }
        private Nullable<global::System.Int32> _LevelSoal;
        partial void OnLevelSoalChanging(Nullable<global::System.Int32> value);
        partial void OnLevelSoalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IbuKota
        {
            get
            {
                return _IbuKota;
            }
            set
            {
                OnIbuKotaChanging(value);
                ReportPropertyChanging("IbuKota");
                _IbuKota = StructuralObject.SetValidValue(value, true, "IbuKota");
                ReportPropertyChanged("IbuKota");
                OnIbuKotaChanged();
            }
        }
        private global::System.String _IbuKota;
        partial void OnIbuKotaChanging(global::System.String value);
        partial void OnIbuKotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LuasWilayah
        {
            get
            {
                return _LuasWilayah;
            }
            set
            {
                OnLuasWilayahChanging(value);
                ReportPropertyChanging("LuasWilayah");
                _LuasWilayah = StructuralObject.SetValidValue(value, true, "LuasWilayah");
                ReportPropertyChanged("LuasWilayah");
                OnLuasWilayahChanged();
            }
        }
        private global::System.String _LuasWilayah;
        partial void OnLuasWilayahChanging(global::System.String value);
        partial void OnLuasWilayahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suku
        {
            get
            {
                return _Suku;
            }
            set
            {
                OnSukuChanging(value);
                ReportPropertyChanging("Suku");
                _Suku = StructuralObject.SetValidValue(value, true, "Suku");
                ReportPropertyChanged("Suku");
                OnSukuChanged();
            }
        }
        private global::System.String _Suku;
        partial void OnSukuChanging(global::System.String value);
        partial void OnSukuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BajuAdat
        {
            get
            {
                return _BajuAdat;
            }
            set
            {
                OnBajuAdatChanging(value);
                ReportPropertyChanging("BajuAdat");
                _BajuAdat = StructuralObject.SetValidValue(value, true, "BajuAdat");
                ReportPropertyChanged("BajuAdat");
                OnBajuAdatChanged();
            }
        }
        private global::System.String _BajuAdat;
        partial void OnBajuAdatChanging(global::System.String value);
        partial void OnBajuAdatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RumahAdat
        {
            get
            {
                return _RumahAdat;
            }
            set
            {
                OnRumahAdatChanging(value);
                ReportPropertyChanging("RumahAdat");
                _RumahAdat = StructuralObject.SetValidValue(value, true, "RumahAdat");
                ReportPropertyChanged("RumahAdat");
                OnRumahAdatChanged();
            }
        }
        private global::System.String _RumahAdat;
        partial void OnRumahAdatChanging(global::System.String value);
        partial void OnRumahAdatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BahasaDaerah
        {
            get
            {
                return _BahasaDaerah;
            }
            set
            {
                OnBahasaDaerahChanging(value);
                ReportPropertyChanging("BahasaDaerah");
                _BahasaDaerah = StructuralObject.SetValidValue(value, true, "BahasaDaerah");
                ReportPropertyChanged("BahasaDaerah");
                OnBahasaDaerahChanged();
            }
        }
        private global::System.String _BahasaDaerah;
        partial void OnBahasaDaerahChanging(global::System.String value);
        partial void OnBahasaDaerahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Flora
        {
            get
            {
                return _Flora;
            }
            set
            {
                OnFloraChanging(value);
                ReportPropertyChanging("Flora");
                _Flora = StructuralObject.SetValidValue(value, true, "Flora");
                ReportPropertyChanged("Flora");
                OnFloraChanged();
            }
        }
        private global::System.String _Flora;
        partial void OnFloraChanging(global::System.String value);
        partial void OnFloraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fauna
        {
            get
            {
                return _Fauna;
            }
            set
            {
                OnFaunaChanging(value);
                ReportPropertyChanging("Fauna");
                _Fauna = StructuralObject.SetValidValue(value, true, "Fauna");
                ReportPropertyChanged("Fauna");
                OnFaunaChanged();
            }
        }
        private global::System.String _Fauna;
        partial void OnFaunaChanging(global::System.String value);
        partial void OnFaunaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PotensiAlam
        {
            get
            {
                return _PotensiAlam;
            }
            set
            {
                OnPotensiAlamChanging(value);
                ReportPropertyChanging("PotensiAlam");
                _PotensiAlam = StructuralObject.SetValidValue(value, true, "PotensiAlam");
                ReportPropertyChanged("PotensiAlam");
                OnPotensiAlamChanged();
            }
        }
        private global::System.String _PotensiAlam;
        partial void OnPotensiAlamChanging(global::System.String value);
        partial void OnPotensiAlamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TempatWisata
        {
            get
            {
                return _TempatWisata;
            }
            set
            {
                OnTempatWisataChanging(value);
                ReportPropertyChanging("TempatWisata");
                _TempatWisata = StructuralObject.SetValidValue(value, true, "TempatWisata");
                ReportPropertyChanged("TempatWisata");
                OnTempatWisataChanged();
            }
        }
        private global::System.String _TempatWisata;
        partial void OnTempatWisataChanging(global::System.String value);
        partial void OnTempatWisataChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NusantaraModel", "FK_PlayerSoal_Provinsi", "PlayerSoal")]
        public PlayerSoal PlayerSoal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PlayerSoal>("NusantaraModel.FK_PlayerSoal_Provinsi", "PlayerSoal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PlayerSoal>("NusantaraModel.FK_PlayerSoal_Provinsi", "PlayerSoal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PlayerSoal> PlayerSoalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PlayerSoal>("NusantaraModel.FK_PlayerSoal_Provinsi", "PlayerSoal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PlayerSoal>("NusantaraModel.FK_PlayerSoal_Provinsi", "PlayerSoal", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NusantaraModel", Name="Setting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Setting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Setting object.
        /// </summary>
        /// <param name="settingId">Initial value of the SettingId property.</param>
        public static Setting CreateSetting(global::System.Int32 settingId)
        {
            Setting setting = new Setting();
            setting.SettingId = settingId;
            return setting;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SettingId
        {
            get
            {
                return _SettingId;
            }
            set
            {
                if (_SettingId != value)
                {
                    OnSettingIdChanging(value);
                    ReportPropertyChanging("SettingId");
                    _SettingId = StructuralObject.SetValidValue(value, "SettingId");
                    ReportPropertyChanged("SettingId");
                    OnSettingIdChanged();
                }
            }
        }
        private global::System.Int32 _SettingId;
        partial void OnSettingIdChanging(global::System.Int32 value);
        partial void OnSettingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GambarBenar
        {
            get
            {
                return _GambarBenar;
            }
            set
            {
                OnGambarBenarChanging(value);
                ReportPropertyChanging("GambarBenar");
                _GambarBenar = StructuralObject.SetValidValue(value, true, "GambarBenar");
                ReportPropertyChanged("GambarBenar");
                OnGambarBenarChanged();
            }
        }
        private global::System.String _GambarBenar;
        partial void OnGambarBenarChanging(global::System.String value);
        partial void OnGambarBenarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GambarSalah
        {
            get
            {
                return _GambarSalah;
            }
            set
            {
                OnGambarSalahChanging(value);
                ReportPropertyChanging("GambarSalah");
                _GambarSalah = StructuralObject.SetValidValue(value, true, "GambarSalah");
                ReportPropertyChanged("GambarSalah");
                OnGambarSalahChanged();
            }
        }
        private global::System.String _GambarSalah;
        partial void OnGambarSalahChanging(global::System.String value);
        partial void OnGambarSalahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GambarBelum
        {
            get
            {
                return _GambarBelum;
            }
            set
            {
                OnGambarBelumChanging(value);
                ReportPropertyChanging("GambarBelum");
                _GambarBelum = StructuralObject.SetValidValue(value, true, "GambarBelum");
                ReportPropertyChanged("GambarBelum");
                OnGambarBelumChanged();
            }
        }
        private global::System.String _GambarBelum;
        partial void OnGambarBelumChanging(global::System.String value);
        partial void OnGambarBelumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ScoreAwal
        {
            get
            {
                return _ScoreAwal;
            }
            set
            {
                OnScoreAwalChanging(value);
                ReportPropertyChanging("ScoreAwal");
                _ScoreAwal = StructuralObject.SetValidValue(value, "ScoreAwal");
                ReportPropertyChanged("ScoreAwal");
                OnScoreAwalChanged();
            }
        }
        private Nullable<global::System.Int32> _ScoreAwal;
        partial void OnScoreAwalChanging(Nullable<global::System.Int32> value);
        partial void OnScoreAwalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NyawaAwal
        {
            get
            {
                return _NyawaAwal;
            }
            set
            {
                OnNyawaAwalChanging(value);
                ReportPropertyChanging("NyawaAwal");
                _NyawaAwal = StructuralObject.SetValidValue(value, "NyawaAwal");
                ReportPropertyChanged("NyawaAwal");
                OnNyawaAwalChanged();
            }
        }
        private Nullable<global::System.Int32> _NyawaAwal;
        partial void OnNyawaAwalChanging(Nullable<global::System.Int32> value);
        partial void OnNyawaAwalChanged();

        #endregion

    }

    #endregion

}
