//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NusantaraGame
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NusantaraEntities1 : DbContext
    {
        public NusantaraEntities1()
            : base("name=NusantaraEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Player> Players { get; set; }
        public DbSet<PlayerSoal> PlayerSoals { get; set; }
        public DbSet<Provinsi> Provinsis { get; set; }
        public DbSet<Setting> Settings { get; set; }
    }
}
