//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NusantaraGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        private string p;
        private int skorawal;
        private int nyawaawal;
        private int p1;

        public Player()
        {
            this.PlayerSoals = new HashSet<PlayerSoal>();
        }

        public Player(int id, int skorawal, int nyawaawal)
        {
            this.PlayerId = id;
            this.LastScore = skorawal;
            this.LastNyawa = nyawaawal;
        }
        public int PlayerId { get; set; }
        public Nullable<int> LastNyawa { get; set; }
        public Nullable<int> LastScore { get; set; }
    
        public virtual ICollection<PlayerSoal> PlayerSoals { get; set; }
    }
}
