//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NusantaraGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerSoal
    {
        public int SoalId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public string Status { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Provinsi Provinsi { get; set; }
    }
}
