//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NusantaraGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingId { get; set; }
        public string GambarBenar { get; set; }
        public string GambarSalah { get; set; }
        public string GambarBelum { get; set; }
        public Nullable<int> ScoreAwal { get; set; }
        public Nullable<int> NyawaAwal { get; set; }
    }
}
